const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),http=require('node:http'),readline=require('node:readline');
const {spawn}=require('node:child_process');
test('structured tasks, interactive questions, concurrent chats and loop decisions',{timeout:60000},async t=>{
  const dir=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'omh-workflow-')));
  await fs.writeFile(path.join(dir,'read.txt'),'test');
  await fs.writeFile(path.join(dir,'range.txt'),'first\nsecond\nthird\nfourth');
  const process=spawn('dotnet',[path.resolve(__dirname,'../../src/OhMyHarness.Service/bin/Release/net10.0/OhMyHarness.Service.dll'),'--database',path.join(dir,'database.sqlite')],{stdio:['pipe','pipe','pipe'],windowsHide:true,env:{...global.process.env,OHMYHARNESS_SKILLS_DIR:path.join(dir,'skills')}});
  let seq=0,readyResolve,readyReject,stderr='',autoAnswer=false,decisions=0,emptySummary=false,holdSummary=false,summaryPending=false,releaseSummary;const pending=new Map(),events=[],payloads=[];
  const ready=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});
  const write=value=>process.stdin.write(JSON.stringify(value)+'\n');
  const rpc=(method,parameters={})=>new Promise((resolve,reject)=>{const id=String(++seq);pending.set(id,{resolve,reject});write({id,method,parameters});});
  process.stderr.on('data',s=>stderr+=s);process.on('error',readyReject);process.on('exit',()=>{readyReject(new Error(stderr));for(const p of pending.values())p.reject(new Error(stderr||'exited'));});
  readline.createInterface({input:process.stdout}).on('line',line=>{
    const item=JSON.parse(line);if(item.ready)return readyResolve();
    if(item.event){events.push(item);if(item.event==='question'&&autoAnswer){decisions++;rpc('question.answer',{id:item.id,chatId:item.chatId,cancelled:false,answers:[['Continuer une fois / Continue once']]}).catch(()=>{});}return;}
    if(item.hostRequest)return write({hostResponse:item.hostRequest,error:'Unexpected host request'});
    const p=pending.get(item.id);if(p){pending.delete(item.id);item.error?p.reject(new Error(item.error)):p.resolve(item.result);}
  });
  const questions=[{question:'Format ?',options:[{label:'HTML',description:'Standalone'},{label:'Texte',description:'Simple'}],custom:false},{question:'Titre ?',options:[]}];
  const server=http.createServer(async(req,res)=>{
    const chunks=[];for await(const c of req)chunks.push(c);const body=JSON.parse(Buffer.concat(chunks));payloads.push(body);
    if(body.messages[0].content.startsWith('Summarize this conversation segment')){
      const finish=()=>{res.writeHead(200,{'Content-Type':'text/event-stream'});res.end('data: '+JSON.stringify({choices:[{delta:{content:emptySummary?'':'Résumé compact.'}}]})+'\n\ndata: [DONE]\n\n');};
      if(holdSummary){summaryPending=true;releaseSummary=finish;}else finish();return;
    }
    const prompt=body.messages.filter(x=>x.role==='user').at(-1).content,previous=body.messages.filter(x=>x.role==='tool');let delta={content:'Done'};
    const tool=(name,args)=>({tool_calls:[{index:0,id:'tool'+previous.length,type:'function',function:{name,arguments:JSON.stringify(args)}}]});
    if(prompt==='questions'&&!previous.length)delta=tool('question',{questions});
    if(prompt==='tasks'&&previous.length<2)delta=tool('todowrite',{todos:[{content:'Inspecter',status:previous.length?'completed':'in_progress'},{content:'Valider',status:'pending'}]});
    if(prompt==='loop'&&previous.length<14)delta=tool('read_source',{path:'read.txt'});
    if(prompt==='range'&&!previous.length)delta=tool('read_source',{path:'range.txt',start_line:2,end_line:3});
    if(prompt==='terminals'){
      const id=n=>JSON.parse(previous[n].content).id;
      const command=global.process.platform==='win32'?"Write-Output 'started'; Start-Sleep -Seconds 5; Write-Output 'finished'":"printf 'started\\n'; sleep 5; printf 'finished\\n'";
      switch(previous.length){
        case 0:delta=tool('create_terminal',{name:'Parallel A'});break;
        case 1:delta=tool('create_terminal',{name:'Parallel B'});break;
        case 2:delta=tool('start_terminal',{terminal_id:id(0),command});break;
        case 3:delta=tool('start_terminal',{terminal_id:id(1),command});break;
        case 4:case 7:delta=tool('list_terminals',{});break;
        case 5:delta=tool('wait_terminal',{terminal_id:id(0),timeout_ms:30000});break;
        case 6:delta=tool('wait_terminal',{terminal_id:id(1),timeout_ms:30000});break;
      }
    }
    res.writeHead(200,{'Content-Type':'text/event-stream'});res.end('data: '+JSON.stringify({choices:[{delta}]})+'\n\ndata: [DONE]\n\n');
  });
  await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{process.stdin.end();process.kill();server.close();});await ready;
  const project=await rpc('project.save',{name:'Workflow',folders:[dir]});
  const provider=await rpc('provider.save',{name:'Fixture',kind:'openai',baseUrl:`http://127.0.0.1:${server.address().port}/v1`,model:'test'});
  await rpc('state.save',{enabledSkills:'sources',permissionMode:'allow',autoContinue:true});
  const create=()=>rpc('chat.save',{projectId:project.id,title:'Test'}),send=(chat,text)=>rpc('send',{chatId:chat.id,providerId:provider.id,text});
  const waitFor=async fn=>{const until=Date.now()+10000;while(Date.now()<until){const result=fn();if(result)return result;await new Promise(r=>setTimeout(r,20));}throw new Error('Timed out');};
  const a=await create();await rpc('chat.modes',{id:a.id,executionMode:'plan',orchestrationMode:'disabled'});
  const ranged=await create();await send(ranged,'range');
  const excerpt=(await rpc('history',{chatId:ranged.id})).find(x=>x.role==='tool').content;
  assert.ok(excerpt.includes('2: second\n3: third\n')&&!excerpt.includes('first')&&!excerpt.includes('fourth'));
  let finished=false;const work=send(a,'questions').then(()=>finished=true);
  const q=await waitFor(()=>events.find(x=>x.event==='question'&&x.chatId===a.id));
  await assert.rejects(rpc('context.compact',{chatId:a.id,providerId:provider.id}),/Wait/);
  const b=await create();await send(b,'other chat');assert.equal(finished,false,'question must suspend only its own chat');
  await rpc('state.save',{language:'en'});assert.equal(finished,false,'settings must not answer or stop the question');
  await assert.rejects(rpc('question.answer',{id:q.id,chatId:b.id,cancelled:false,answers:[['HTML'],['Rapport']]}));
  await assert.rejects(rpc('question.answer',{id:q.id,chatId:a.id,cancelled:false,answers:[['invented'],['Rapport']]}));
  assert.ok((await rpc('snapshot')).questions.some(x=>x.id===q.id));
  await rpc('question.answer',{id:q.id,chatId:a.id,cancelled:false,answers:[['HTML'],['Rapport']]});await work;
  assert.ok((await rpc('history',{chatId:a.id})).some(x=>x.role==='interaction'&&x.content.includes('Rapport')));
  assert.ok(payloads.some(x=>x.messages.some(m=>m.role==='tool'&&m.content.includes('Rapport'))));
  await assert.rejects(rpc('question.answer',{id:q.id,chatId:a.id,cancelled:true,answers:[]}));
  const c=await create();await send(c,'tasks');const tasks=(await rpc('history',{chatId:c.id})).filter(x=>x.role==='tasks');assert.equal(tasks.length,1);assert.equal(JSON.parse(tasks[0].content)[0].status,'completed');
  await send(c,'resume');assert.ok(payloads.at(-1).messages[0].content.includes('Current structured tasks'));
  const d=await create();const loop=send(d,'loop').catch(error=>error);
  const decision=await waitFor(()=>events.find(x=>x.event==='question'&&x.chatId===d.id));
  assert.equal((await rpc('history',{chatId:d.id})).filter(x=>x.role==='tool').length,2,'third tool must not run before decision');
  await rpc('question.answer',{id:decision.id,chatId:d.id,cancelled:false,answers:[['Arrêter / Stop']]});assert.ok(await loop instanceof Error);
  assert.equal((await rpc('snapshot')).questions.length,0);
  autoAnswer=true;const e=await create();await send(e,'loop');autoAnswer=false;
  assert.equal(decisions,12,'each repeated call remains guarded across the 12-step auto-continue boundary');
  assert.equal((await rpc('history',{chatId:e.id})).filter(x=>x.role==='tool').length,14);
  const f=await create();const stopped=send(f,'questions').catch(error=>error);const pendingQ=await waitFor(()=>events.find(x=>x.event==='question'&&x.chatId===f.id));await rpc('stop',{chatId:f.id});assert.ok(await stopped instanceof Error);assert.equal((await rpc('snapshot')).questions.length,0);
  await assert.rejects(rpc('question.answer',{id:pendingQ.id,chatId:f.id,cancelled:false,answers:[['HTML'],['Late']]}));
  const g=await create();const dismissed=send(g,'questions');const dismissedQ=await waitFor(()=>events.find(x=>x.event==='question'&&x.chatId===g.id));await rpc('question.answer',{id:dismissedQ.id,chatId:g.id,cancelled:true,answers:[]});await dismissed;
  assert.ok((await rpc('history',{chatId:g.id})).some(x=>x.role==='tool'&&x.content.includes('"cancelled":true')));
  const before=await rpc('context.details',{chatId:c.id,providerId:provider.id});assert.ok(before.activeMessages>0&&before.tools>0);
  const compact=await rpc('context.compact',{chatId:c.id,providerId:provider.id});assert.equal(compact.changed,true);assert.ok(compact.details.used<before.used);
  const compacted=await rpc('history',{chatId:c.id});assert.ok(compacted.some(x=>x.state==='compacted'));assert.equal(compacted.filter(x=>x.state==='complete').length,1);assert.ok(compacted.some(x=>x.role==='tasks'));
  assert.equal((await rpc('context.compact',{chatId:c.id,providerId:provider.id})).changed,false);
  const h=await create();await send(h,'Long request '.repeat(100));const original=await rpc('history',{chatId:h.id});emptySummary=true;
  await assert.rejects(rpc('context.compact',{chatId:h.id,providerId:provider.id}));assert.deepEqual(await rpc('history',{chatId:h.id}),original);emptySummary=false;
  holdSummary=true;const compacting=rpc('context.compact',{chatId:h.id,providerId:provider.id}).catch(e=>e);await waitFor(()=>summaryPending);
  await assert.rejects(send(h,'cannot interleave'));await rpc('stop',{chatId:h.id});assert.ok(await compacting instanceof Error);releaseSummary();
  assert.deepEqual(await rpc('history',{chatId:h.id}),original);assert.equal((await rpc('snapshot')).running.includes(h.id),false);
  const sandboxChat=await create();
  await rpc('chat.modes',{id:sandboxChat.id,sandboxEnabled:true});
  assert.equal((await rpc('snapshot')).chats.find(x=>x.id===sandboxChat.id).sandboxEnabled,true);
  let review=await rpc('sandbox.review',{chatId:sandboxChat.id});assert.equal(review.count,0);await rpc('sandbox.close',{token:review.token});
  const hash=require('node:crypto').createHash('sha256').update(path.join(dir,'database.sqlite')).digest('hex').toUpperCase().slice(0,16);
  const sandboxRoot=path.join(dir,'sandboxes',hash,String(sandboxChat.id),'work',path.basename(dir));
  await fs.writeFile(path.join(sandboxRoot,'read.txt'),'sandbox output');
  review=await rpc('sandbox.review',{chatId:sandboxChat.id});assert.equal(review.count,1);assert.ok(review.diff.includes('+sandbox output'));
  assert.equal(await fs.readFile(path.join(dir,'read.txt'),'utf8'),'test','review never writes original, even with global auto-approval');
  await assert.rejects(rpc('sandbox.apply',{chatId:c.id,token:review.token}),/expired/);
  review=await rpc('sandbox.review',{chatId:sandboxChat.id});await fs.writeFile(path.join(dir,'read.txt'),'external edit');
  await assert.rejects(rpc('sandbox.apply',{chatId:sandboxChat.id,token:review.token}),/chang/);
  await fs.writeFile(path.join(dir,'read.txt'),'test');review=await rpc('sandbox.review',{chatId:sandboxChat.id});
  await rpc('sandbox.apply',{chatId:sandboxChat.id,token:review.token});assert.equal(await fs.readFile(path.join(dir,'read.txt'),'utf8'),'sandbox output');
  await assert.rejects(rpc('sandbox.apply',{chatId:sandboxChat.id,token:review.token}),/expired/);
  const openCode=await rpc('provider.save',{name:'Unisolated OpenCode',kind:'opencode',baseUrl:'http://127.0.0.1:9',model:'fixture'});
  await assert.rejects(rpc('send',{chatId:sandboxChat.id,providerId:openCode.id,text:'sandbox'}),/OpenCode.*not supported/);
  assert.equal((await rpc('history',{chatId:sandboxChat.id})).length,0,'unsupported provider fails before message/inference');
  await rpc('state.save',{enabledSkills:'sources,terminal'});
  const terminalChat=await create(),parallel=send(terminalChat,'terminals');
  await waitFor(()=>events.find(x=>x.event==='status'&&x.chatId===terminalChat.id&&x.text.includes('wait_terminal')));
  const tabs=await rpc('terminals.list',{chatId:terminalChat.id});assert.equal(tabs.length,2);assert.ok(tabs.every(t=>t.status==='running'));
  const other=await create();await send(other,'unrelated conversation');
  await assert.rejects(rpc('terminals.stop',{chatId:other.id,terminalId:tabs[0].id}));
  await parallel;
  const finishedTabs=await rpc('terminals.list',{chatId:terminalChat.id});assert.ok(finishedTabs.every(t=>t.status==='completed'&&t.output.includes('finished')));
  const terminalHistory=await rpc('history',{chatId:terminalChat.id});assert.ok(terminalHistory.some(m=>m.role==='tool'&&m.content.startsWith('list_terminals')&&(m.content.match(/"status":"running"/g)||[]).length===2));
  await rpc('terminals.delete',{chatId:terminalChat.id,terminalId:tabs[0].id});assert.equal((await rpc('terminals.list',{chatId:terminalChat.id})).length,1);
});
